/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressSelector: typeof import('./components/AddressSelector.vue')['default']
    AreaPicker: typeof import('./components/common/AreaPicker.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FormInput: typeof import('./components/common/FormInput.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InkHeader: typeof import('./components/InkHeader.vue')['default']
    InkTabBar: typeof import('./components/InkTabBar.vue')['default']
    LoadingState: typeof import('./components/common/LoadingState.vue')['default']
    LogisticsTimeline: typeof import('./components/LogisticsTimeline.vue')['default']
    OrderCard: typeof import('./components/OrderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./components/common/StatusBadge.vue')['default']
  }
}
